### ISSUE TITLE
Add pytest hook

### ISSUE THREAD

**Issue by mateusz2173** [WebSoftDevs/MusicBot2#33]
Add pytest check to our workflow

`pytest app/tests/`

**Comment by xNykram** [comment]
First let me take care of #24.

There will be an issue when the local database will be implemented for testing purposes, do we have some solutions for that? Is there an option to create postgres instance on github runner in order to run tests or should we skip tests which are using database connection?

**Comment by mateusz2173** [comment]
We should separate unit test and integration tests, so we won't encounter problems like that
